import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";
import AuthProvider from "@/services/AuthProvider";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <AuthProvider>
      <body className={inter.className}><div className="h-screen" >
     
        <Navbar/>
        <div className="h-screen flex justify-center items-start">{children}</div>
        <Footer></Footer>
        </div>
       
        </body>
        </AuthProvider>
    </html>
  );
}
